<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7i8nhfs\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7i8nhfs/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7i8nhfs.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7i8nhfs\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container7i8nhfs\appDevDebugProjectContainer(array(
    'container.build_hash' => '7i8nhfs',
    'container.build_id' => '674dea18',
    'container.build_time' => 1537992032,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7i8nhfs');
